In [18]:
import pandas as pd

In [19]:
new_scores = pd.read_csv("/users/1/lundq163/projects/automated-qc/data/known_problems/re-eval_for_CV_data_model_02r7.csv")
new_scores

,subject_id,session_id,run_id,suffix,scan,QCer,Updated QU motion score,QU_motion,predicted_qu_motion_score,abs_error,validation_fold0,validation_fold1,validation_fold2,validation_fold3,validation_fold4,notes
0,sub-100079,ses-V02,1,T2w,sub-100079_ses-V02_run-1_T2w.nii.gz,Begim,2.5,3.0,1.989765,1.010235,0,0,0,1,0,NaN
1,sub-102229,ses-V02,1,T1w,sub-102229_ses-V02_run-1_T1w.nii.gz,Begim,1,1.0,1.528872,0.528872,0,0,0,0,1,NaN
2,sub-102522,ses-V02,1,T2w,sub-102522_ses-V02_run-1_T2w.nii.gz,Begim,1,0.5,1.786466,1.286466,1,0,0,0,0,NaN
3,sub-102666,ses-V02,1,T2w,sub-102666_ses-V02_run-1_T2w.nii.gz,Begim,0.5,0.0,0.826923,0.826923,0,0,0,0,1,NaN
4,sub-103002,ses-V03,2,T1w,sub-103002_ses-V03_run-2_T1w.nii.gz,Begim,1,0.5,1.793439,1.293439,1,0,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
402,sub-205268,ses-V02,1,T2w,sub-205268_ses-V02_run-1_T2w.nii.gz,Begim,1.5,2.5,1.350080,1.149920,0,0,0,1,0,NaN
403,sub-205268,ses-V02,2,T2w,sub-205268_ses-V02_run-2_T2w.nii.gz,Begim,1.5,2.0,1.023212,0.976788,0,0,0,1,0,NaN
404,sub-206064,ses-V03,1,T2w,sub-206064_ses-V03_run-1_T2w.nii.gz,Begim,1,1.5,0.957190,0.542810,1,0,0,0,0,NaN
405,sub-206064,ses-V03,2,T2w,sub-206064_ses-V03_run-2_T2w.nii.gz,Begim,0.5,1.5,0.851769,0.648231,1,0,0,0,0,NaN
406,sub-206064,ses-V04,1,T1w,sub-206064_ses-V04_run-1_T1w.nii.gz,Begim,0.5,0.5,1.143729,0.643729,1,0,0,0,0,NaN

In [20]:
# drop the following columns: 'QU_motion', 'Rater', 'Notes', 'accuracy'
#new_scores = new_scores.drop(columns=['QU_motion', 'Rater', 'Notes', 'accuracy'])
new_scores = new_scores[['scan', 'Updated QU motion score']]
new_scores

                                    scan Updated QU motion score
0    sub-100079_ses-V02_run-1_T2w.nii.gz                     2.5
1    sub-102229_ses-V02_run-1_T1w.nii.gz                       1
2    sub-102522_ses-V02_run-1_T2w.nii.gz                       1
3    sub-102666_ses-V02_run-1_T2w.nii.gz                     0.5
4    sub-103002_ses-V03_run-2_T1w.nii.gz                       1
..                                   ...                     ...
402  sub-205268_ses-V02_run-1_T2w.nii.gz                     1.5
403  sub-205268_ses-V02_run-2_T2w.nii.gz                     1.5
404  sub-206064_ses-V03_run-1_T2w.nii.gz                       1
405  sub-206064_ses-V03_run-2_T2w.nii.gz                     0.5
406  sub-206064_ses-V04_run-1_T1w.nii.gz                     0.5

[407 rows x 2 columns]

In [21]:
# load in current data set
#current_scores = pd.read_csv("/users/1/lundq163/projects/automated-qc/data/raw/auto_qc_t1w_t2w_subset_1024r.csv")
current_scores = pd.read_csv("/users/1/lundq163/projects/automated-qc/data/raw/auto_qc_t1w_t2w_subset_1024r_curated.csv")
current_scores

,subject_id,session_id,run_id,suffix,scan,QU_motion
0,sub-100079,ses-V02,1,T2w,sub-100079_ses-V02_run-1_T2w.nii.gz,3.0
1,sub-100247,ses-V02,1,T2w,sub-100247_ses-V02_run-1_T2w.nii.gz,3.0
2,sub-100524,ses-V02,1,T2w,sub-100524_ses-V02_run-1_T2w.nii.gz,1.0
3,sub-100586,ses-V02,1,T2w,sub-100586_ses-V02_run-1_T2w.nii.gz,0.5
4,sub-100895,ses-V02,1,T2w,sub-100895_ses-V02_run-1_T2w.nii.gz,1.0
...,...,...,...,...,...,...
1019,sub-206064,ses-V02,1,T1w,sub-206064_ses-V02_run-1_T1w.nii.gz,3.0
1020,sub-206064,ses-V03,1,T2w,sub-206064_ses-V03_run-1_T2w.nii.gz,1.5
1021,sub-206064,ses-V03,2,T2w,sub-206064_ses-V03_run-2_T2w.nii.gz,1.5
1022,sub-206064,ses-V04,1,T1w,sub-206064_ses-V04_run-1_T1w.nii.gz,0.5
1023,sub-206064,ses-V04,1,T2w,sub-206064_ses-V04_run-1_T2w.nii.gz,0.5

In [22]:
# merge the two dataframes on the scan column
merged_scores = current_scores.merge(new_scores, on='scan', how='left')
merged_scores

,subject_id,session_id,run_id,suffix,scan,QU_motion,Updated QU motion score
0,sub-100079,ses-V02,1,T2w,sub-100079_ses-V02_run-1_T2w.nii.gz,3.0,2.5
1,sub-100247,ses-V02,1,T2w,sub-100247_ses-V02_run-1_T2w.nii.gz,3.0,NaN
2,sub-100524,ses-V02,1,T2w,sub-100524_ses-V02_run-1_T2w.nii.gz,1.0,NaN
3,sub-100586,ses-V02,1,T2w,sub-100586_ses-V02_run-1_T2w.nii.gz,0.5,NaN
4,sub-100895,ses-V02,1,T2w,sub-100895_ses-V02_run-1_T2w.nii.gz,1.0,NaN
...,...,...,...,...,...,...,...
1019,sub-206064,ses-V02,1,T1w,sub-206064_ses-V02_run-1_T1w.nii.gz,3.0,NaN
1020,sub-206064,ses-V03,1,T2w,sub-206064_ses-V03_run-1_T2w.nii.gz,1.5,1
1021,sub-206064,ses-V03,2,T2w,sub-206064_ses-V03_run-2_T2w.nii.gz,1.5,0.5
1022,sub-206064,ses-V04,1,T1w,sub-206064_ses-V04_run-1_T1w.nii.gz,0.5,0.5
1023,sub-206064,ses-V04,1,T2w,sub-206064_ses-V04_run-1_T2w.nii.gz,0.5,NaN

In [23]:
# rename the 'Updated QU motion score' column to 'corrected_QU_motion'
merged_scores = merged_scores.rename(columns={'Updated QU motion score': 'corrected_QU_motion'})
merged_scores

,subject_id,session_id,run_id,suffix,scan,QU_motion,corrected_QU_motion
0,sub-100079,ses-V02,1,T2w,sub-100079_ses-V02_run-1_T2w.nii.gz,3.0,2.5
1,sub-100247,ses-V02,1,T2w,sub-100247_ses-V02_run-1_T2w.nii.gz,3.0,NaN
2,sub-100524,ses-V02,1,T2w,sub-100524_ses-V02_run-1_T2w.nii.gz,1.0,NaN
3,sub-100586,ses-V02,1,T2w,sub-100586_ses-V02_run-1_T2w.nii.gz,0.5,NaN
4,sub-100895,ses-V02,1,T2w,sub-100895_ses-V02_run-1_T2w.nii.gz,1.0,NaN
...,...,...,...,...,...,...,...
1019,sub-206064,ses-V02,1,T1w,sub-206064_ses-V02_run-1_T1w.nii.gz,3.0,NaN
1020,sub-206064,ses-V03,1,T2w,sub-206064_ses-V03_run-1_T2w.nii.gz,1.5,1
1021,sub-206064,ses-V03,2,T2w,sub-206064_ses-V03_run-2_T2w.nii.gz,1.5,0.5
1022,sub-206064,ses-V04,1,T1w,sub-206064_ses-V04_run-1_T1w.nii.gz,0.5,0.5
1023,sub-206064,ses-V04,1,T2w,sub-206064_ses-V04_run-1_T2w.nii.gz,0.5,NaN

In [24]:
# if there are any missing values in the 'corrected_QU_motion' column, fill them with the original 'QU_motion' scores
merged_scores['corrected_QU_motion'] = merged_scores['corrected_QU_motion'].fillna(merged_scores['QU_motion'])
merged_scores

,subject_id,session_id,run_id,suffix,scan,QU_motion,corrected_QU_motion
0,sub-100079,ses-V02,1,T2w,sub-100079_ses-V02_run-1_T2w.nii.gz,3.0,2.5
1,sub-100247,ses-V02,1,T2w,sub-100247_ses-V02_run-1_T2w.nii.gz,3.0,3.0
2,sub-100524,ses-V02,1,T2w,sub-100524_ses-V02_run-1_T2w.nii.gz,1.0,1.0
3,sub-100586,ses-V02,1,T2w,sub-100586_ses-V02_run-1_T2w.nii.gz,0.5,0.5
4,sub-100895,ses-V02,1,T2w,sub-100895_ses-V02_run-1_T2w.nii.gz,1.0,1.0
...,...,...,...,...,...,...,...
1019,sub-206064,ses-V02,1,T1w,sub-206064_ses-V02_run-1_T1w.nii.gz,3.0,3.0
1020,sub-206064,ses-V03,1,T2w,sub-206064_ses-V03_run-1_T2w.nii.gz,1.5,1
1021,sub-206064,ses-V03,2,T2w,sub-206064_ses-V03_run-2_T2w.nii.gz,1.5,0.5
1022,sub-206064,ses-V04,1,T1w,sub-206064_ses-V04_run-1_T1w.nii.gz,0.5,0.5
1023,sub-206064,ses-V04,1,T2w,sub-206064_ses-V04_run-1_T2w.nii.gz,0.5,0.5

In [25]:
# drop rows where corrected_QU_motion is NaN
merged_scores = merged_scores.dropna(subset=['corrected_QU_motion'])
merged_scores

,subject_id,session_id,run_id,suffix,scan,QU_motion,corrected_QU_motion
0,sub-100079,ses-V02,1,T2w,sub-100079_ses-V02_run-1_T2w.nii.gz,3.0,2.5
1,sub-100247,ses-V02,1,T2w,sub-100247_ses-V02_run-1_T2w.nii.gz,3.0,3.0
2,sub-100524,ses-V02,1,T2w,sub-100524_ses-V02_run-1_T2w.nii.gz,1.0,1.0
3,sub-100586,ses-V02,1,T2w,sub-100586_ses-V02_run-1_T2w.nii.gz,0.5,0.5
4,sub-100895,ses-V02,1,T2w,sub-100895_ses-V02_run-1_T2w.nii.gz,1.0,1.0
...,...,...,...,...,...,...,...
1019,sub-206064,ses-V02,1,T1w,sub-206064_ses-V02_run-1_T1w.nii.gz,3.0,3.0
1020,sub-206064,ses-V03,1,T2w,sub-206064_ses-V03_run-1_T2w.nii.gz,1.5,1
1021,sub-206064,ses-V03,2,T2w,sub-206064_ses-V03_run-2_T2w.nii.gz,1.5,0.5
1022,sub-206064,ses-V04,1,T1w,sub-206064_ses-V04_run-1_T1w.nii.gz,0.5,0.5
1023,sub-206064,ses-V04,1,T2w,sub-206064_ses-V04_run-1_T2w.nii.gz,0.5,0.5

In [26]:
# save as new csv
merged_scores.to_csv("/users/1/lundq163/projects/automated-qc/data/raw/auto_qc_t1w_t2w_subset_1024r_fixed_from_model02r7_corrections.csv", index=False)

In [27]:
# reload merged scores
merged_scores_curated = pd.read_csv("/users/1/lundq163/projects/automated-qc/data/raw/auto_qc_t1w_t2w_subset_1024r_fixed_from_model02r7_corrections.csv")
merged_scores_curated

,subject_id,session_id,run_id,suffix,scan,QU_motion,corrected_QU_motion
0,sub-100079,ses-V02,1,T2w,sub-100079_ses-V02_run-1_T2w.nii.gz,3.0,2.5
1,sub-100247,ses-V02,1,T2w,sub-100247_ses-V02_run-1_T2w.nii.gz,3.0,3.0
2,sub-100524,ses-V02,1,T2w,sub-100524_ses-V02_run-1_T2w.nii.gz,1.0,1.0
3,sub-100586,ses-V02,1,T2w,sub-100586_ses-V02_run-1_T2w.nii.gz,0.5,0.5
4,sub-100895,ses-V02,1,T2w,sub-100895_ses-V02_run-1_T2w.nii.gz,1.0,1.0
...,...,...,...,...,...,...,...
1019,sub-206064,ses-V02,1,T1w,sub-206064_ses-V02_run-1_T1w.nii.gz,3.0,3.0
1020,sub-206064,ses-V03,1,T2w,sub-206064_ses-V03_run-1_T2w.nii.gz,1.5,1
1021,sub-206064,ses-V03,2,T2w,sub-206064_ses-V03_run-2_T2w.nii.gz,1.5,0.5
1022,sub-206064,ses-V04,1,T1w,sub-206064_ses-V04_run-1_T1w.nii.gz,0.5,0.5
1023,sub-206064,ses-V04,1,T2w,sub-206064_ses-V04_run-1_T2w.nii.gz,0.5,0.5

In [28]:
# drop "QU_motion" column
merged_scores_curated = merged_scores_curated.drop(columns=['QU_motion'])
merged_scores_curated

,subject_id,session_id,run_id,suffix,scan,corrected_QU_motion
0,sub-100079,ses-V02,1,T2w,sub-100079_ses-V02_run-1_T2w.nii.gz,2.5
1,sub-100247,ses-V02,1,T2w,sub-100247_ses-V02_run-1_T2w.nii.gz,3.0
2,sub-100524,ses-V02,1,T2w,sub-100524_ses-V02_run-1_T2w.nii.gz,1.0
3,sub-100586,ses-V02,1,T2w,sub-100586_ses-V02_run-1_T2w.nii.gz,0.5
4,sub-100895,ses-V02,1,T2w,sub-100895_ses-V02_run-1_T2w.nii.gz,1.0
...,...,...,...,...,...,...
1019,sub-206064,ses-V02,1,T1w,sub-206064_ses-V02_run-1_T1w.nii.gz,3.0
1020,sub-206064,ses-V03,1,T2w,sub-206064_ses-V03_run-1_T2w.nii.gz,1
1021,sub-206064,ses-V03,2,T2w,sub-206064_ses-V03_run-2_T2w.nii.gz,0.5
1022,sub-206064,ses-V04,1,T1w,sub-206064_ses-V04_run-1_T1w.nii.gz,0.5
1023,sub-206064,ses-V04,1,T2w,sub-206064_ses-V04_run-1_T2w.nii.gz,0.5

In [29]:
# rename "corrected_QU_motion" to "QU_motion"
merged_scores_curated = merged_scores_curated.rename(columns={'corrected_QU_motion': 'QU_motion'})
merged_scores_curated

,subject_id,session_id,run_id,suffix,scan,QU_motion
0,sub-100079,ses-V02,1,T2w,sub-100079_ses-V02_run-1_T2w.nii.gz,2.5
1,sub-100247,ses-V02,1,T2w,sub-100247_ses-V02_run-1_T2w.nii.gz,3.0
2,sub-100524,ses-V02,1,T2w,sub-100524_ses-V02_run-1_T2w.nii.gz,1.0
3,sub-100586,ses-V02,1,T2w,sub-100586_ses-V02_run-1_T2w.nii.gz,0.5
4,sub-100895,ses-V02,1,T2w,sub-100895_ses-V02_run-1_T2w.nii.gz,1.0
...,...,...,...,...,...,...
1019,sub-206064,ses-V02,1,T1w,sub-206064_ses-V02_run-1_T1w.nii.gz,3.0
1020,sub-206064,ses-V03,1,T2w,sub-206064_ses-V03_run-1_T2w.nii.gz,1
1021,sub-206064,ses-V03,2,T2w,sub-206064_ses-V03_run-2_T2w.nii.gz,0.5
1022,sub-206064,ses-V04,1,T1w,sub-206064_ses-V04_run-1_T1w.nii.gz,0.5
1023,sub-206064,ses-V04,1,T2w,sub-206064_ses-V04_run-1_T2w.nii.gz,0.5

In [30]:
# save the merged dataframe to a new csv
merged_scores_curated.to_csv("/users/1/lundq163/projects/automated-qc/data/raw/auto_qc_t1w_t2w_subset_1024r_curated_from_model02r7_corrections.csv", index=False)